hazelcast:
  static:
    itemCacheName: itemCache
    itemIdQueueName: itemIdQueue
  config:
    cacheConfigs:
      itemCache:
        name: ${hazelcast.static.itemCacheName}
        backupCount: 2
    queueConfigs:
      itemIdQueue:
        name: ${hazelcast.static.itemIdQueueName}
        backupCount: 2

