spring:
  application:
    name: producer
  profiles:
    active: ignite

logging:
  level:
    com.devkwondo: DEBUG

consumer:
  itemsToConsume: 100
  parallelism: 2
  sleepDuration: 100

server:
  port: 0