ignite:
  static:
    itemCacheName: itemCache
    itemIdQueueName: itemIdQueue
  queue:
    item-id:
      cacheMode: PARTITIONED
      atomicyMode: ATOMIC
      backups: 1
      collocated: false
  streamer:
    bufferSize: 100
    autoFlushFrequency: 20
  config:
    clientMode: true
    cacheConfiguration:
      - name: ${ignite.static.itemCacheName}
        cacheMode: PARTITIONED
        atomicyMode: TRANSACTIONAL
        backups: 1



