spring:
  application:
    name: producer
  profiles:
    active: ignite

producer:
  itemsToProduce: 100
  parallelism: 2
  minPayloadSize: 1024
  maxPayloadSize: 1024

logging:
  level:
    com.devkwondo: DEBUG

server:
  port: 0